/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Felipe
 */
public class Informacoes extends javax.swing.JFrame {

    /**
     * Creates new form Informacoes
     */
    public Informacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BarraMenu = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        Desenvolvedores = new javax.swing.JPanel();
        Allef1 = new javax.swing.JLabel();
        Eduardo1 = new javax.swing.JLabel();
        Felipe1 = new javax.swing.JLabel();
        Lucas1 = new javax.swing.JLabel();
        Rafael1 = new javax.swing.JLabel();
        Vinicius1 = new javax.swing.JLabel();
        RGMalef1 = new javax.swing.JLabel();
        RGMeduardo1 = new javax.swing.JLabel();
        RGMfelipe1 = new javax.swing.JLabel();
        RGMlucas1 = new javax.swing.JLabel();
        RGMrafael1 = new javax.swing.JLabel();
        RGMvinicius1 = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Infromacoes"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BarraMenu.setBackground(new java.awt.Color(0, 28, 119));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("DESENVOLVEDORES");

        javax.swing.GroupLayout BarraMenuLayout = new javax.swing.GroupLayout(BarraMenu);
        BarraMenu.setLayout(BarraMenuLayout);
        BarraMenuLayout.setHorizontalGroup(
            BarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(1100, Short.MAX_VALUE))
        );
        BarraMenuLayout.setVerticalGroup(
            BarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Desenvolvedores.setBackground(new java.awt.Color(0, 28, 119));

        Allef1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Allef1.setForeground(new java.awt.Color(255, 255, 255));
        Allef1.setText("ALLEF SOUSA SANTOS");

        Eduardo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Eduardo1.setForeground(new java.awt.Color(255, 255, 255));
        Eduardo1.setText("EDUARDO FELÍCIO BORGES");

        Felipe1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Felipe1.setForeground(new java.awt.Color(255, 255, 255));
        Felipe1.setText("FELIPE APARECIDO TOFANIN ARAÚJO");

        Lucas1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Lucas1.setForeground(new java.awt.Color(255, 255, 255));
        Lucas1.setText("LUCAS SILVA MARTINS");

        Rafael1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rafael1.setForeground(new java.awt.Color(255, 255, 255));
        Rafael1.setText("RAFAEL GOMES CALDAS");

        Vinicius1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Vinicius1.setForeground(new java.awt.Color(255, 255, 255));
        Vinicius1.setText("VINICIUS MAIA BARBOSA");

        RGMalef1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RGMalef1.setForeground(new java.awt.Color(255, 255, 255));
        RGMalef1.setText("14.001.276");

        RGMeduardo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RGMeduardo1.setForeground(new java.awt.Color(255, 255, 255));
        RGMeduardo1.setText("14.053.063");

        RGMfelipe1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RGMfelipe1.setForeground(new java.awt.Color(255, 255, 255));
        RGMfelipe1.setText("14.021.803");

        RGMlucas1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RGMlucas1.setForeground(new java.awt.Color(255, 255, 255));
        RGMlucas1.setText("14.004.780");

        RGMrafael1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RGMrafael1.setForeground(new java.awt.Color(255, 255, 255));
        RGMrafael1.setText("14.002.957");

        RGMvinicius1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RGMvinicius1.setForeground(new java.awt.Color(255, 255, 255));
        RGMvinicius1.setText("14.001.098");

        Titulo1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("DESENVOLVEDORES");

        javax.swing.GroupLayout DesenvolvedoresLayout = new javax.swing.GroupLayout(Desenvolvedores);
        Desenvolvedores.setLayout(DesenvolvedoresLayout);
        DesenvolvedoresLayout.setHorizontalGroup(
            DesenvolvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesenvolvedoresLayout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addGroup(DesenvolvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DesenvolvedoresLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(Titulo1))
                    .addGroup(DesenvolvedoresLayout.createSequentialGroup()
                        .addGroup(DesenvolvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DesenvolvedoresLayout.createSequentialGroup()
                                .addGroup(DesenvolvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rafael1)
                                    .addComponent(Lucas1)
                                    .addComponent(Felipe1)
                                    .addComponent(Eduardo1)
                                    .addComponent(Allef1))
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DesenvolvedoresLayout.createSequentialGroup()
                                .addComponent(Vinicius1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(DesenvolvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RGMrafael1)
                            .addComponent(RGMlucas1)
                            .addComponent(RGMfelipe1)
                            .addComponent(RGMeduardo1)
                            .addComponent(RGMalef1)
                            .addComponent(RGMvinicius1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DesenvolvedoresLayout.setVerticalGroup(
            DesenvolvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesenvolvedoresLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(Titulo1)
                .addGap(40, 40, 40)
                .addGroup(DesenvolvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DesenvolvedoresLayout.createSequentialGroup()
                        .addComponent(RGMalef1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RGMeduardo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RGMfelipe1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RGMlucas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RGMrafael1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DesenvolvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RGMvinicius1)
                            .addComponent(Vinicius1)))
                    .addGroup(DesenvolvedoresLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Allef1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Eduardo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Felipe1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Lucas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rafael1)))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Unifran.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Desenvolvedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(475, 475, 475)
                .addComponent(Imagem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BarraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Imagem)
                .addGap(25, 25, 25)
                .addComponent(Desenvolvedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.dispose();
    }//GEN-LAST:event_formMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Allef1;
    private javax.swing.JPanel BarraMenu;
    private javax.swing.JPanel Desenvolvedores;
    private javax.swing.JLabel Eduardo1;
    private javax.swing.JLabel Felipe1;
    private javax.swing.JLabel Imagem;
    private javax.swing.JLabel Lucas1;
    private javax.swing.JLabel RGMalef1;
    private javax.swing.JLabel RGMeduardo1;
    private javax.swing.JLabel RGMfelipe1;
    private javax.swing.JLabel RGMlucas1;
    private javax.swing.JLabel RGMrafael1;
    private javax.swing.JLabel RGMvinicius1;
    private javax.swing.JLabel Rafael1;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Vinicius1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
