package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Funcionalidades.AbrirNavegador;
import Funcionalidades.Atualizahora;
import Model.ModeloLogin;
import View.Login;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author Felipe
 */
public class Menu extends javax.swing.JFrame {
   CadastrarFuncionario ViewFuncionario = new CadastrarFuncionario();
    int aux=0;
    // Objeto para Abrir Navegador 
    AbrirNavegador abrirPagina = new AbrirNavegador();
    // Metodo que recebe Filial Passada pela tela de LOGIN 
   public void Recebendoctd(String a){
      // Adicionando o valor recebido a tela 
       lblUnidade.setText(a);
   }
    
    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setIcon();
        Menu.setVisible(false);
       // lblUnidade.setText(modellogin.getCentroOn().toString());
        /**
         * Instanciando a classe atualiza hora
         */
        
        Atualizahora HoraData = new Atualizahora();
      
        
        
        /**
         * chamando o metodo para atualizar hora
         * @param Jdata
         */
        HoraData.StartData(Jdata);
        /**
         * chamando o metodo para atualizar hora 
         * @param Jhora
         */
        HoraData.StartHora(Jhora);
       
    }
    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("2.png")));
    }
    
        public void cor(){
            
            btnCadastrar.setBackground(new java.awt.Color(0,28,119));
            btnPedidos.setBackground(new java.awt.Color(0,28,119));
                            
            
        }
         
        public void ocultarBotoes(){
            //Primeira Parte
            btnMenu1.setVisible(false);
            btnMenu2.setVisible(false);
            btnMenu3.setVisible(false);
            btnMenu4.setVisible(false);
            btnMenu5.setVisible(false);
            btnMenu6.setVisible(false);
            btnMenu7.setVisible(false);
            btnMenu8.setVisible(false);
            btnMenu9.setVisible(false);
            btnMenu10.setVisible(false);
            
            //Segunda parte
            btnMenu11.setVisible(false);
            btnMenu12.setVisible(false);
            btnMenu13.setVisible(false);
            btnMenu13.setVisible(false);
            btnMenu14.setVisible(false);
            btnMenu15.setVisible(false);
            btnMenu16.setVisible(false);

            
                 
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BarraMenu = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSair1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        btnRecolhe2 = new javax.swing.JButton();
        btnRecolhe1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnMenu1 = new javax.swing.JButton();
        btnMenu2 = new javax.swing.JButton();
        btnMenu3 = new javax.swing.JButton();
        btnMenu4 = new javax.swing.JButton();
        btnMenu5 = new javax.swing.JButton();
        btnMenu6 = new javax.swing.JButton();
        btnMenu7 = new javax.swing.JButton();
        btnMenu8 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnMenu11 = new javax.swing.JButton();
        btnMenu12 = new javax.swing.JButton();
        btnMenu13 = new javax.swing.JButton();
        btnMenu14 = new javax.swing.JButton();
        btnMenu10 = new javax.swing.JButton();
        btnMenu9 = new javax.swing.JButton();
        btnMenu15 = new javax.swing.JButton();
        btnMenu16 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnCadastrar = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        btnPedidos = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnLogout = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnInformações = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jPanel7 = new javax.swing.JPanel();
        lblUnidade1 = new javax.swing.JLabel();
        lblUnidade = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        Jdata = new javax.swing.JLabel();
        Jhora = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Menu"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BarraMenu.setBackground(new java.awt.Color(0, 28, 119));

        btnSair.setBackground(new java.awt.Color(0, 28, 119));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Sair.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setFocusPainted(false);
        btnSair.setMaximumSize(new java.awt.Dimension(30, 30));
        btnSair.setMinimumSize(new java.awt.Dimension(30, 30));
        btnSair.setPreferredSize(new java.awt.Dimension(30, 30));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");

        btnSair1.setBackground(new java.awt.Color(0, 28, 119));
        btnSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Minimizar.png"))); // NOI18N
        btnSair1.setBorder(null);
        btnSair1.setBorderPainted(false);
        btnSair1.setFocusPainted(false);
        btnSair1.setMaximumSize(new java.awt.Dimension(30, 30));
        btnSair1.setMinimumSize(new java.awt.Dimension(30, 30));
        btnSair1.setPreferredSize(new java.awt.Dimension(30, 30));
        btnSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraMenuLayout = new javax.swing.GroupLayout(BarraMenu);
        BarraMenu.setLayout(BarraMenuLayout);
        BarraMenuLayout.setHorizontalGroup(
            BarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BarraMenuLayout.setVerticalGroup(
            BarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BarraMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(btnSair1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Menu.setBackground(new java.awt.Color(0, 28, 119));
        Menu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Menu.setEnabled(false);

        btnRecolhe2.setBackground(new java.awt.Color(0, 28, 119));
        btnRecolhe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Recolher.png"))); // NOI18N
        btnRecolhe2.setBorder(null);
        btnRecolhe2.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnRecolhe2.setFocusable(false);
        btnRecolhe2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecolhe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecolhe2ActionPerformed(evt);
            }
        });

        btnRecolhe1.setBackground(new java.awt.Color(0, 28, 119));
        btnRecolhe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Recolher.png"))); // NOI18N
        btnRecolhe1.setBorder(null);
        btnRecolhe1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnRecolhe1.setFocusable(false);
        btnRecolhe1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecolhe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecolhe1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 28, 119));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        btnMenu1.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu1.setText("jButton10");
        btnMenu1.setBorder(null);
        btnMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu1.setFocusPainted(false);
        btnMenu1.setFocusable(false);
        btnMenu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu1.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu1.setPreferredSize(new java.awt.Dimension(135, 25));
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });

        btnMenu2.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu2.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu2.setText("jButton11");
        btnMenu2.setBorder(null);
        btnMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu2.setFocusPainted(false);
        btnMenu2.setFocusable(false);
        btnMenu2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu2.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu2.setPreferredSize(new java.awt.Dimension(135, 25));
        btnMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu2ActionPerformed(evt);
            }
        });

        btnMenu3.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu3.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu3.setText("jButton12");
        btnMenu3.setBorder(null);
        btnMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu3.setFocusPainted(false);
        btnMenu3.setFocusable(false);
        btnMenu3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu3.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu3.setPreferredSize(new java.awt.Dimension(135, 25));
        btnMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu3ActionPerformed(evt);
            }
        });

        btnMenu4.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu4.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu4.setText("jButton13");
        btnMenu4.setBorder(null);
        btnMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu4.setFocusPainted(false);
        btnMenu4.setFocusable(false);
        btnMenu4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu4.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu4.setPreferredSize(new java.awt.Dimension(135, 25));
        btnMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu4ActionPerformed(evt);
            }
        });

        btnMenu5.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu5.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu5.setText("jButton14");
        btnMenu5.setBorder(null);
        btnMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu5.setFocusPainted(false);
        btnMenu5.setFocusable(false);
        btnMenu5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu5.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu5.setPreferredSize(new java.awt.Dimension(135, 25));
        btnMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu5ActionPerformed(evt);
            }
        });

        btnMenu6.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu6.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu6.setText("jButton15");
        btnMenu6.setBorder(null);
        btnMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu6.setFocusPainted(false);
        btnMenu6.setFocusable(false);
        btnMenu6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu6.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu6.setPreferredSize(new java.awt.Dimension(135, 25));
        btnMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu6ActionPerformed(evt);
            }
        });

        btnMenu7.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu7.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu7.setText("jButton16");
        btnMenu7.setBorder(null);
        btnMenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu7.setFocusPainted(false);
        btnMenu7.setFocusable(false);
        btnMenu7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu7.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu7.setPreferredSize(new java.awt.Dimension(135, 25));
        btnMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu7ActionPerformed(evt);
            }
        });

        btnMenu8.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu8.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu8.setText("jButton17");
        btnMenu8.setBorder(null);
        btnMenu8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu8.setFocusPainted(false);
        btnMenu8.setFocusable(false);
        btnMenu8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu8.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu8.setPreferredSize(new java.awt.Dimension(135, 25));
        btnMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 28, 119));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        btnMenu11.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu11.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu11.setText("EMPRESA");
        btnMenu11.setBorder(null);
        btnMenu11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu11.setFocusPainted(false);
        btnMenu11.setFocusable(false);
        btnMenu11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu11.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu11.setPreferredSize(new java.awt.Dimension(135, 25));

        btnMenu12.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu12.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu12.setText("PRODUTOS");
        btnMenu12.setBorder(null);
        btnMenu12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu12.setFocusPainted(false);
        btnMenu12.setFocusable(false);
        btnMenu12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu12.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu12.setPreferredSize(new java.awt.Dimension(135, 25));

        btnMenu13.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu13.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu13.setText("jButton12");
        btnMenu13.setBorder(null);
        btnMenu13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu13.setFocusPainted(false);
        btnMenu13.setFocusable(false);
        btnMenu13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu13.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu13.setPreferredSize(new java.awt.Dimension(135, 25));

        btnMenu14.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu14.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu14.setText("jButton13");
        btnMenu14.setBorder(null);
        btnMenu14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu14.setFocusPainted(false);
        btnMenu14.setFocusable(false);
        btnMenu14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu14.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu14.setPreferredSize(new java.awt.Dimension(135, 25));

        btnMenu10.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu10.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu10.setText("jButton19");
        btnMenu10.setBorder(null);
        btnMenu10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu10.setFocusPainted(false);
        btnMenu10.setFocusable(false);
        btnMenu10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu10.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu10.setPreferredSize(new java.awt.Dimension(135, 25));

        btnMenu9.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu9.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu9.setText("jButton18");
        btnMenu9.setBorder(null);
        btnMenu9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu9.setFocusPainted(false);
        btnMenu9.setFocusable(false);
        btnMenu9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu9.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu9.setPreferredSize(new java.awt.Dimension(135, 25));

        btnMenu15.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu15.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu15.setText("jButton14");
        btnMenu15.setBorder(null);
        btnMenu15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu15.setFocusPainted(false);
        btnMenu15.setFocusable(false);
        btnMenu15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu15.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu15.setPreferredSize(new java.awt.Dimension(135, 25));

        btnMenu16.setBackground(new java.awt.Color(40, 68, 159));
        btnMenu16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu16.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu16.setText("jButton15");
        btnMenu16.setBorder(null);
        btnMenu16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu16.setFocusPainted(false);
        btnMenu16.setFocusable(false);
        btnMenu16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu16.setMinimumSize(new java.awt.Dimension(135, 25));
        btnMenu16.setPreferredSize(new java.awt.Dimension(135, 25));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(btnMenu9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnMenu9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMenu10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnMenu15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMenu16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnMenu11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMenu12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMenu13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMenu14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(btnRecolhe1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecolhe2))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRecolhe2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRecolhe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jToolBar2.setBackground(new java.awt.Color(0, 28, 119));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.add(jSeparator4);

        btnCadastrar.setBackground(new java.awt.Color(0, 28, 119));
        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cadastrar.png"))); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setBorder(null);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setFocusable(false);
        btnCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrar.setMaximumSize(new java.awt.Dimension(150, 60));
        btnCadastrar.setMinimumSize(new java.awt.Dimension(150, 60));
        btnCadastrar.setPreferredSize(new java.awt.Dimension(170, 60));
        btnCadastrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnCadastrar);
        jToolBar2.add(jSeparator12);

        btnPedidos.setBackground(new java.awt.Color(0, 28, 119));
        btnPedidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Pedidos.png"))); // NOI18N
        btnPedidos.setText("PEDIDOS");
        btnPedidos.setBorder(null);
        btnPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedidos.setFocusable(false);
        btnPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPedidos.setMaximumSize(new java.awt.Dimension(150, 60));
        btnPedidos.setMinimumSize(new java.awt.Dimension(150, 60));
        btnPedidos.setPreferredSize(new java.awt.Dimension(170, 60));
        btnPedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPedidosMouseEntered(evt);
            }
        });
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        jToolBar2.add(btnPedidos);
        jToolBar2.add(jSeparator13);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jToolBar1.setBackground(new java.awt.Color(0, 28, 119));
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(1290, 60));
        jToolBar1.add(jSeparator1);

        btnLogout.setBackground(new java.awt.Color(0, 28, 119));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/LogOut.png"))); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.setBorder(null);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMaximumSize(new java.awt.Dimension(110, 60));
        btnLogout.setMinimumSize(new java.awt.Dimension(110, 60));
        btnLogout.setPreferredSize(new java.awt.Dimension(110, 60));
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);
        jToolBar1.add(jSeparator2);

        btnInformações.setBackground(new java.awt.Color(0, 28, 119));
        btnInformações.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnInformações.setForeground(new java.awt.Color(255, 255, 255));
        btnInformações.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Informações.png"))); // NOI18N
        btnInformações.setText("INFORMAÇÕES");
        btnInformações.setBorder(null);
        btnInformações.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInformações.setFocusable(false);
        btnInformações.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInformações.setMaximumSize(new java.awt.Dimension(110, 60));
        btnInformações.setMinimumSize(new java.awt.Dimension(110, 60));
        btnInformações.setPreferredSize(new java.awt.Dimension(110, 60));
        btnInformações.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInformações.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformaçõesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInformações);
        jToolBar1.add(jSeparator5);
        jToolBar1.add(jSeparator7);

        jPanel7.setBackground(new java.awt.Color(0, 28, 119));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        lblUnidade1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUnidade1.setForeground(new java.awt.Color(255, 255, 255));
        lblUnidade1.setText("UNIDADE:");
        lblUnidade1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUnidade1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUnidade1MouseClicked(evt);
            }
        });

        lblUnidade.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUnidade.setForeground(new java.awt.Color(255, 255, 255));
        lblUnidade.setText(" Unidade");
        lblUnidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUnidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUnidadeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUnidade1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(707, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUnidade1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUnidade)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel7);

        jButton1.setBackground(new java.awt.Color(0, 28, 119));
        jButton1.setBorder(null);
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(300, 10));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator10);

        Jdata.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Jdata.setForeground(new java.awt.Color(255, 255, 255));
        Jdata.setText("dd/mm/aaaa");
        jToolBar1.add(Jdata);

        Jhora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Jhora.setForeground(new java.awt.Color(255, 255, 255));
        Jhora.setText(" ");
        jToolBar1.add(Jhora);

        jButton2.setBackground(new java.awt.Color(0, 28, 119));
        jButton2.setBorder(null);
        jButton2.setEnabled(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setBackground(new java.awt.Color(0, 28, 119));
        jButton3.setBorder(null);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(503, 503, 503)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BarraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Menu.setVisible(true);
        ocultarBotoes();
        aux =1;
        cor();
        
        btnCadastrar.setBackground(new java.awt.Color(0, 102, 255));
        
        btnMenu1.setVisible(true);
        btnMenu1.setText(" EMPRESA");
       // btnMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenus/Veiculos.png"))); // NOI18N
        
        btnMenu2.setVisible(true);
        btnMenu2.setText(" CLIENTE");
       // btnMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenus/Veiculos.png"))); // NOI18N
        
        btnMenu3.setVisible(true);
        btnMenu3.setText(" FUNCIONARIO");
       // btnMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenus/Veiculos.png"))); // NOI18N
        
        btnMenu4.setVisible(true);
        btnMenu4.setText(" VEICULO");
        //btnMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenus/Veiculos.png"))); // NOI18N
        
        btnMenu5.setVisible(true);
        btnMenu5.setText(" ROTA");
        //btnMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenus/Veiculos.png"))); // NOI18N
        
       
      
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair1ActionPerformed
       setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnSair1ActionPerformed

    private void btnRecolhe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecolhe1ActionPerformed
        Menu.setVisible(false);
        cor();
    }//GEN-LAST:event_btnRecolhe1ActionPerformed

    private void btnRecolhe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecolhe2ActionPerformed
        Menu.setVisible(false);
        cor();
    }//GEN-LAST:event_btnRecolhe2ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        if (aux==1)
            new CadastrarEmpresa().setVisible(true);
        
        if (aux==3){
        LocalizaPedido loc = new LocalizaPedido();
        loc.setVisible(true);
        }
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu5ActionPerformed
        if (aux==1){
            CadastraRota rota = new CadastraRota();
            rota.setVisible(true);}
    }//GEN-LAST:event_btnMenu5ActionPerformed

    private void btnMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu2ActionPerformed
        if (aux==1)
            new CadastroCliente().setVisible(true);
        
           if (aux==3){            
            new EntradaUnidade().setVisible(true);
        }
    }//GEN-LAST:event_btnMenu2ActionPerformed

    private void btnMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu3ActionPerformed
        if (aux==1){
            ViewFuncionario.recebendoFilial(lblUnidade.getText());
            ViewFuncionario.setVisible(true);
           }
            
            if (aux==3){
            new EntregaPedido().setVisible(true);
        }
    }//GEN-LAST:event_btnMenu3ActionPerformed

    private void btnMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu4ActionPerformed
        if (aux==1)
            new CadastrarVeiculos().setVisible(true);
        
           if (aux==3) {
               new SaidaPedido().setVisible(true);
           }
    }//GEN-LAST:event_btnMenu4ActionPerformed

    private void btnMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu6ActionPerformed
  
    }//GEN-LAST:event_btnMenu6ActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        Menu.setVisible(true);
        ocultarBotoes();
        aux =3;
        cor();
        btnPedidos.setBackground(new java.awt.Color(0, 102, 255));
        
        btnMenu1.setVisible(true);
        btnMenu1.setText(" LOCALIZAR");
       // btnMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenus/Veiculos.png"))); // NOI18N
        
        btnMenu2.setVisible(true);
        btnMenu2.setText(" ENTRADA");
       // btnMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenus/Veiculos.png"))); // NOI18N
        
        btnMenu3.setVisible(true);
        btnMenu3.setText(" ENTREGAS");
       // btnMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenus/Veiculos.png"))); // NOI18N
        
        btnMenu4.setVisible(true);
        btnMenu4.setText(" SAÍDA");
       // btnMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenus/Veiculos.png"))); // NOI18N
        
        

        
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu7ActionPerformed
       // if (aux==1)
         //   new CadastroMaquinas().setVisible(true);
    }//GEN-LAST:event_btnMenu7ActionPerformed

    private void btnMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu8ActionPerformed
        // if (aux==1)
         //   new CadastroProfissionais().setVisible(true);
    }//GEN-LAST:event_btnMenu8ActionPerformed

    private void btnInformaçõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformaçõesActionPerformed
        new Informacoes().setVisible(true);
    }//GEN-LAST:event_btnInformaçõesActionPerformed

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        PesquisaEmpresa  emp= new PesquisaEmpresa();
        emp.setVisible(true);
    }//GEN-LAST:event_jPanel7MouseClicked

    private void btnPedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPedidosMouseEntered

    private void lblUnidade1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUnidade1MouseClicked
         PesquisaEmpresa  emp= new PesquisaEmpresa();
        emp.setVisible(true);
    }//GEN-LAST:event_lblUnidade1MouseClicked

    private void lblUnidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUnidadeMouseClicked
        PesquisaEmpresa  emp= new PesquisaEmpresa();
        emp.setVisible(true);
    }//GEN-LAST:event_lblUnidadeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraMenu;
    private javax.swing.JLabel Jdata;
    private javax.swing.JLabel Jhora;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnInformações;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnMenu10;
    private javax.swing.JButton btnMenu11;
    private javax.swing.JButton btnMenu12;
    private javax.swing.JButton btnMenu13;
    private javax.swing.JButton btnMenu14;
    private javax.swing.JButton btnMenu15;
    private javax.swing.JButton btnMenu16;
    private javax.swing.JButton btnMenu2;
    private javax.swing.JButton btnMenu3;
    private javax.swing.JButton btnMenu4;
    private javax.swing.JButton btnMenu5;
    private javax.swing.JButton btnMenu6;
    private javax.swing.JButton btnMenu7;
    private javax.swing.JButton btnMenu8;
    private javax.swing.JButton btnMenu9;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnRecolhe1;
    private javax.swing.JButton btnRecolhe2;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSair1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JLabel lblUnidade1;
    // End of variables declaration//GEN-END:variables
}
