/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.ConnBanco;
import Dao.DaoVeiculo;
import Funcionalidades.ModeloTabela;
import Model.Veiculo;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Rafael
 */
public class PesquisarVeiculo extends javax.swing.JFrame {

    CadastrarVeiculos EnviandoObjeto;
    Veiculo veic = new Veiculo();
    DaoVeiculo daoVeic = new DaoVeiculo();
    ConnBanco connBanco = new ConnBanco();
    /**
     * Creates new form PesquisarVeiculo
     */
    
    public PesquisarVeiculo() {
        initComponents();
        connBanco.getConection();
        preencherTabela("SELECT * FROM veiculo order by id_Veiculo;");
    }
    
    public void preencherTabela(String SQL) {
        int cidade, funcionario;
        Long unidade;
        String cid = null,uni,sql1,sql,sql2,fun;
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID Veiculo", "Placa", "Nº Chassi", "Capacidade", "Modelo", "Centro Dist", "Funcionario", "Cidade"};
        
        connBanco.executaSQL(SQL);
        // pegando o primeiro registro 
        try {
            connBanco.rs.first();

            // pegando os valores e formatando para preecher a tabela  
            do {
                cidade = connBanco.rs.getInt("fk_Id_Cidade");
                sql = "SELECT nome FROM cidade where id = ?";
                cid = daoVeic.chaveEstrangeira(sql, cidade);
                
                unidade = connBanco.rs.getLong("fk_Id_Centro_Dist");
                sql1 = "SELECT nome_Fantasia from centro_dist where cnpj =?";
                uni = daoVeic.chaveEstrangeiraLong(sql1, unidade);
                
                funcionario = connBanco.rs.getInt("fk_Id_Func");
                sql2 = "SELECT nome FROM funcionario where id = ?";
                fun = daoVeic.chaveEstrangeira(sql2, funcionario);
                
                dados.add(new Object[]{connBanco.rs.getInt("id_Veiculo"), connBanco.rs.getString("placa"), connBanco.rs.getString("num_Chassi"), connBanco.rs.getInt("capacidade"),
                     connBanco.rs.getString("modelo"), uni, fun, cid});
            } while (connBanco.rs.next());
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        // colocando os devidos valores em suas colunas 
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tabelaVeiculo.setModel(modelo);
        tabelaVeiculo.getColumnModel().getColumn(0).setPreferredWidth(80);
        tabelaVeiculo.getColumnModel().getColumn(0).setResizable(true);
        tabelaVeiculo.getColumnModel().getColumn(1).setPreferredWidth(120);
        tabelaVeiculo.setSelectionBackground(Color.lightGray);
        tabelaVeiculo.setSelectionForeground(Color.BLUE);

        tabelaVeiculo.getColumnModel().getColumn(1).setResizable(true);
        tabelaVeiculo.getColumnModel().getColumn(2).setPreferredWidth(120);
        tabelaVeiculo.getColumnModel().getColumn(2).setResizable(false);
        tabelaVeiculo.getColumnModel().getColumn(3).setPreferredWidth(120);
        tabelaVeiculo.getColumnModel().getColumn(3).setResizable(false);
        tabelaVeiculo.getColumnModel().getColumn(4).setPreferredWidth(120);
        tabelaVeiculo.getColumnModel().getColumn(4).setResizable(false);
        tabelaVeiculo.getColumnModel().getColumn(5).setPreferredWidth(180);
        tabelaVeiculo.getColumnModel().getColumn(5).setResizable(true);
        tabelaVeiculo.getColumnModel().getColumn(6).setPreferredWidth(120);
        tabelaVeiculo.getColumnModel().getColumn(6).setResizable(true);
        tabelaVeiculo.getColumnModel().getColumn(7).setPreferredWidth(100);
        tabelaVeiculo.getColumnModel().getColumn(7).setResizable(true);
        
        //tabelaVeiculo.getTableHeader().setReorderingAllowed(false);*/
        tabelaVeiculo.setAutoResizeMode(tabelaVeiculo.AUTO_RESIZE_OFF);
        tabelaVeiculo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPesquisaNumChassi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisaPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVeiculo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisaIdVeiculo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("ID");

        jLabel3.setText("Nº Chassi");

        jLabel4.setText("Placa");

        btnPesquisar.setText("Pesquisar");

        tabelaVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVeiculo);

        jLabel1.setText("Consultar Veiculo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPesquisaPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(txtPesquisaIdVeiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisaNumChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(399, 399, 399))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisaIdVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPesquisaNumChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVeiculoMouseClicked

        /**
        *
        */
        int linha = tabelaVeiculo.getSelectedRow();
        int codigo = Integer.parseInt(tabelaVeiculo.getValueAt(linha, 0).toString());
        Veiculo recebeVeic;
        recebeVeic = daoVeic.getVeiculo(codigo);

        if (EnviandoObjeto == null) {
            EnviandoObjeto = new CadastrarVeiculos();
            EnviandoObjeto.setVisible(true);
            EnviandoObjeto.recebendo(recebeVeic);
            this.setVisible(false);
        } else {
            EnviandoObjeto.setVisible(true);
            EnviandoObjeto.setState(CadastrarFuncionario.NORMAL);
            EnviandoObjeto.recebendo(veic);
            this.setVisible(false);
        }
    }//GEN-LAST:event_tabelaVeiculoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVeiculo;
    private javax.swing.JTextField txtPesquisaIdVeiculo;
    private javax.swing.JTextField txtPesquisaNumChassi;
    private javax.swing.JTextField txtPesquisaPlaca;
    // End of variables declaration//GEN-END:variables
}
