/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.ConnBanco;
import Dao.DaoVeiculo;
import Funcionalidades.ModeloTabela;
import Model.Veiculo;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Rafael
 */
public class PesquisarVeiculo extends javax.swing.JFrame {

  
    CadastrarVeiculos EnviandoObjeto;
    Veiculo veic = new Veiculo();
    DaoVeiculo daoVeic = new DaoVeiculo();
    ConnBanco connBanco = new ConnBanco();
    /**
     * Creates new form PesquisarVeiculo
     */
    
    public PesquisarVeiculo() {
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        connBanco.getConection();
        preencherTabela("SELECT * FROM veiculo order by id_Veiculo;");
    }
    
    public void preencherTabela(String SQL) {
        int cidade, funcionario;
        Long unidade;
        String cid = null,uni,sql1,sql,sql2,fun;
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID Veiculo", "Placa", "Nº Chassi", "Capacidade", "Modelo", "Centro Dist", "Funcionario", "Cidade"};
        
        connBanco.executaSQL(SQL);
        // pegando o primeiro registro 
        try {
            connBanco.rs.first();

            // pegando os valores e formatando para preecher a tabela  
            do {
                cidade = connBanco.rs.getInt("fk_Id_Cidade");
                sql = "SELECT nome FROM cidade where id = ?";
                cid = daoVeic.chaveEstrangeira(sql, cidade);
                
                unidade = connBanco.rs.getLong("fk_Id_Centro_Dist");
                sql1 = "SELECT nome_Fantasia from centro_dist where cnpj =?";
                uni = daoVeic.chaveEstrangeiraLong(sql1, unidade);
                
                funcionario = connBanco.rs.getInt("fk_Id_Func");
                sql2 = "SELECT nome FROM funcionario where id = ?";
                fun = daoVeic.chaveEstrangeira(sql2, funcionario);
                
                dados.add(new Object[]{connBanco.rs.getInt("id_Veiculo"), connBanco.rs.getString("placa"),
                    connBanco.rs.getString("num_Chassi"), connBanco.rs.getInt("capacidade"),
                     connBanco.rs.getString("modelo"), uni, fun, cid/*connBanco.rs.getString("fk_Id_Centro_Dist"),
                     connBanco.rs.getString("fk_Id_Func"), connBanco.rs.getString("fk_id_Cidade")*/});
            } while (connBanco.rs.next());
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        // colocando os devidos valores em suas colunas 
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tabelaVeiculo.setModel(modelo);
        tabelaVeiculo.getColumnModel().getColumn(0).setPreferredWidth(80);
        tabelaVeiculo.getColumnModel().getColumn(0).setResizable(true);
        tabelaVeiculo.getColumnModel().getColumn(1).setPreferredWidth(120);
        tabelaVeiculo.setSelectionBackground(Color.lightGray);
        tabelaVeiculo.setSelectionForeground(Color.BLUE);
        tabelaVeiculo.getColumnModel().getColumn(1).setResizable(true);
        tabelaVeiculo.getColumnModel().getColumn(2).setPreferredWidth(120);
        tabelaVeiculo.getColumnModel().getColumn(2).setResizable(false);
        tabelaVeiculo.getColumnModel().getColumn(3).setPreferredWidth(120);
        tabelaVeiculo.getColumnModel().getColumn(3).setResizable(false);
        tabelaVeiculo.getColumnModel().getColumn(4).setPreferredWidth(120);
        tabelaVeiculo.getColumnModel().getColumn(4).setResizable(false);
        tabelaVeiculo.getColumnModel().getColumn(5).setPreferredWidth(180);
        tabelaVeiculo.getColumnModel().getColumn(5).setResizable(true);
        tabelaVeiculo.getColumnModel().getColumn(6).setPreferredWidth(120);
        tabelaVeiculo.getColumnModel().getColumn(6).setResizable(true);
        tabelaVeiculo.getColumnModel().getColumn(7).setPreferredWidth(100);
        tabelaVeiculo.getColumnModel().getColumn(7).setResizable(true);
        
        tabelaVeiculo.getTableHeader().setReorderingAllowed(false);
        tabelaVeiculo.setAutoResizeMode(tabelaVeiculo.AUTO_RESIZE_OFF);
        tabelaVeiculo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVeiculo = new javax.swing.JTable();
        txtPesquisaIdVeiculo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisaNumChassi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BarraMenu3 = new javax.swing.JPanel();
        btnSair3 = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnSair4 = new javax.swing.JButton();
        txtPesquisaPlaca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabelaVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVeiculo);

        txtPesquisaIdVeiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("CODIGO:");

        txtPesquisaNumChassi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nº CHASSI:");

        btnPesquisar.setBackground(new java.awt.Color(0, 28, 119));
        btnPesquisar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Pesquisa.png"))); // NOI18N
        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.setToolTipText("PESQUISAR");
        btnPesquisar.setFocusPainted(false);
        btnPesquisar.setFocusable(false);
        btnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("PLACA:");

        BarraMenu3.setBackground(new java.awt.Color(0, 28, 119));

        btnSair3.setBackground(new java.awt.Color(0, 28, 119));
        btnSair3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Sair.png"))); // NOI18N
        btnSair3.setBorder(null);
        btnSair3.setBorderPainted(false);
        btnSair3.setFocusPainted(false);
        btnSair3.setMaximumSize(new java.awt.Dimension(30, 30));
        btnSair3.setMinimumSize(new java.awt.Dimension(30, 30));
        btnSair3.setPreferredSize(new java.awt.Dimension(30, 30));
        btnSair3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair3ActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("PESQUISAR VEICULOS");

        btnSair4.setBackground(new java.awt.Color(0, 28, 119));
        btnSair4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Minimizar.png"))); // NOI18N
        btnSair4.setBorder(null);
        btnSair4.setBorderPainted(false);
        btnSair4.setFocusPainted(false);
        btnSair4.setMaximumSize(new java.awt.Dimension(30, 30));
        btnSair4.setMinimumSize(new java.awt.Dimension(30, 30));
        btnSair4.setPreferredSize(new java.awt.Dimension(30, 30));
        btnSair4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraMenu3Layout = new javax.swing.GroupLayout(BarraMenu3);
        BarraMenu3.setLayout(BarraMenu3Layout);
        BarraMenu3Layout.setHorizontalGroup(
            BarraMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraMenu3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BarraMenu3Layout.setVerticalGroup(
            BarraMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSair3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BarraMenu3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnSair4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtPesquisaPlaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPesquisaPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaPlacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPesquisaNumChassi, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(txtPesquisaIdVeiculo)
                    .addComponent(txtPesquisaPlaca))
                .addGap(33, 33, 33)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(598, 598, 598))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BarraMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPesquisaIdVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesquisaNumChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPesquisaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVeiculoMouseClicked

        int linha = tabelaVeiculo.getSelectedRow();
        int codigo = Integer.parseInt(tabelaVeiculo.getValueAt(linha, 0).toString());
        Veiculo recebeVeic;
        recebeVeic = daoVeic.getVeiculo(codigo);

        if (EnviandoObjeto == null) {
            EnviandoObjeto = new CadastrarVeiculos();
            EnviandoObjeto.setVisible(true);
            EnviandoObjeto.recebendo(recebeVeic);
            this.setVisible(false);
        } else {
            EnviandoObjeto.setVisible(true);
            EnviandoObjeto.setState(CadastrarFuncionario.NORMAL);
            EnviandoObjeto.recebendo(veic);
            this.setVisible(false);
        }
    }//GEN-LAST:event_tabelaVeiculoMouseClicked

    private void btnSair3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSair3ActionPerformed

    private void btnSair4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair4ActionPerformed
        this.setExtendedState(Menu.ICONIFIED);
    }//GEN-LAST:event_btnSair4ActionPerformed

    private void txtPesquisaPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraMenu3;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair3;
    private javax.swing.JButton btnSair4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabelaVeiculo;
    private javax.swing.JTextField txtPesquisaIdVeiculo;
    private javax.swing.JTextField txtPesquisaNumChassi;
    private javax.swing.JTextField txtPesquisaPlaca;
    // End of variables declaration//GEN-END:variables
}
